environment=local
driver=chrome
windowMaximize=true
driverPath=../Cucumber_OWN/src/resources/java/drivers/chromedriver.exe
url=https://www.flipkart.com/
implicitlyWait=20
testDataPath=../Cucumber_OWN/src/resources/java/testDataResources/
